-- Runtime database is Google Sheets, not PostgreSQL.
-- This file is kept as a human-readable schema reference only.
--
-- Spreadsheet tabs:
--
-- 1) Overview
--    Columns:
--    ชื่อนักเรียน, ชื่อเล่น, คอร์ส, ระดับ, ครู, วันเรียน, เวลา,
--    วันเริ่มเรียน, ชั่วโมงทั้งหมด, เรียนแล้ว (ชม.), คงเหลือ (ชม.),
--    สถานะ, ผู้ปกครอง, เบอร์โทร
--
-- 2) ตารางเรียน
--    Raw weekly grid exactly as exported from the class schedule file.
--
-- 3) สัปดาห์นี้
--    Columns start at row 2:
--    วันที่, วัน, เวลา, ระยะเวลา, ชื่อนักเรียน, ชื่อเล่น, คอร์ส, ระดับ,
--    ครู, ผู้ปกครอง, เบอร์โทร, ชั่วโมงทั้งหมด, เรียนแล้ว (ชม.),
--    สถานะคอนเฟิร์ม, สถานะการเรียน, then optional available slot columns.
--
